### ISSUE TITLE
ЕГОР ПРОПИШИ ИНКЛЮДЫ ДЛЯ ПАЦАНСКИХ КОМПИЛЯТОРВОВ

### ISSUE THREAD

**Issue by sarnatk** [TheSecondThread/FivaproljoTasks#40]
src/Scene.cpp
НА ПЯТОЙ СТРОЧКЕ ЭТОГО ФАЙЛА ПИШИ
#include <cassert>
ок?

**Comment by LebedevEA** [comment]
@sarnatk Просто `#include`?

**Comment by sarnatk** [comment]
.............гитхабу нужно экранировать пипец
#include \<cassert\>
